<?php
/**
 * @copyright: Copyright © 2017 Firebear Studio. All rights reserved.
 * @author   : Firebear Studio <fbeardev@gmail.com>
 */

$_code = $block->getMethodCode();
$coinpaymentsScope = \Magento\Framework\App\ObjectManager::getInstance()->get('\Magento\Framework\App\Config\ScopeConfigInterface');
if ($coinpaymentsScope->getValue('payment/coinpayments/fullscreen')) {
    echo '<ul class="form-list" id="payment_form_' . $_code . '" style="display:none;">' .
        '<li>You will be transfered to <a href="https://www.coinpayments.net" target="_blank">CoinPayments</a> to complete your purchase when using this payment method.</li>' .
        '</ul>';
}
