<?php
/**
 * @copyright: Copyright © 2017 Firebear Studio. All rights reserved.
 * @author   : Firebear Studio <fbeardev@gmail.com>
 */
// Retrieve order
$orderId     = $block->getLastOrderId();
$payemntData = $block->getPaymentData();
$quoteData   = $block->getQuote();
$successUrl  = $block->getSuccessUrl();
$failUrl     = $block->getFailUrl();
?>
<form name="coinpaymentsform" method="post" action="https://www.coinpayments.net/index.php">
    <input type="hidden" name="cmd" value="_pay_auto">
    <input type="hidden" name="reset" value="1">
    <input type="hidden" name="merchant" value="<?php echo $payemntData['merchant_id']; ?>">
    <input type="hidden" name="item_name" value="<?php echo $payemntData['item_name']; ?> Order">
    <input type="hidden" name="invoice" value="<?php echo $orderId; ?>">
    <input type="hidden" name="custom" value="<?php echo $payemntData['store_id']; ?>">
    <input type="hidden" name="quantity" value="1">
    <input type="hidden" name="allow_quantity" value="0">
    <input type="hidden" name="want_shipping" value="0">
    <input type="hidden" name="currency" value="<?php echo htmlspecialchars(
        $payemntData['currency_code'],
        ENT_QUOTES,
        'utf-8'
    ); ?>">
    <input type="hidden" name="shippingf" value="<?php echo $block->getShippingAmount(); ?>">
    <input type="hidden" name="taxf" value="<?php $quoteData->getShippingAddress()->getTaxAmount(); ?>">
    <input type="hidden" name="amountf" value="<?php echo $quoteData->getSubtotal(); ?>">
    <input type="hidden" name="success_url" value="<?php echo $successUrl; ?>">
    <input type="hidden" name="cancel_url" value="<?php echo $failUrl; ?>">
    <input type="hidden" name="ipn_url" value="<?php echo htmlspecialchars($block->getIpnUrl(), ENT_QUOTES, 'utf-8'); ?>">
    <input type="hidden" name="email" value="<?php echo htmlspecialchars(
        $quoteData->getCustomerEmail(),
        ENT_QUOTES,
        'utf-8'
    ); ?>">
    <input type="hidden" name="first_name" value="<?php echo htmlspecialchars(
        $quoteData->getBillingAddress()->getFirstname(),
        ENT_QUOTES,
        'utf-8'
    ); ?>">
    <input type="hidden" name="last_name" value="<?php echo htmlspecialchars(
        $quoteData->getBillingAddress()->getLastname(),
        ENT_QUOTES,
        'utf-8'
    ); ?>">
    <noscript><input type="submit" value="Click here to complete checkout at CoinPayments.net"></noscript>
</form>
<script type="text/javascript">
    document.coinpaymentsform.submit();
</script>